---
title: "Semana 12"
---

## Leituras interessantes

{{< fa file-pdf size=lg >}} [Teste Rápido para Deteação da Infecção pelo HIV-1 em Gestantes](/artigos/Teste Rapido para Deteccao da Infeccao pelo HIV-1 em Gestantes.pdf)

{{< fa file-pdf size=lg >}} [Avaliação do Teste Rápido Utilizando o Antígeno Recombinante k39 no Diagnóstico da Leishmaniose Visceral no Brasil](/artigos/Avaliação do Teste Rápido Utilizando o Antígeno Recombinante.pdf)


## Entrega lista de exercícios 02

::: callout-important

## Fique Atento!

{{< fa file-lines size=lg >}} [Lista de exercícios 02](/exercicios/lista02.html "Lista de exercícios 02"){aria-label="Lista de exercícios 02"} 

-   Data de entrega:
    -   10 de março de 2025
:::



## Estudo de caso

::: callout-important

## Fique Atento!

{{< fa laptop-file size=lg >}} [Estudo de Caso 04: Avaliação dos testes rápidos Optimal-IT<sup><span>&#174;</span></sup> e ICT P.f./P.v.<sup>&reg;</sup> para o diagnóstico da malária, na Atenção Básica de Saúde, no município de Manaus, Amazonas](/estudos_de_casos/estudo04.html "Estudo de caso 04"){aria-label="Estudo de caso 04"} 

-   Data de entrega:
    -   17 de março de 2025
:::





## Slides

{{< fa file-powerpoint size=lg >}} [Testes diagnósticos](/aulas/Testes%20diagnósticos/testesDiagnosticos.html#/valor-de-predição-de-um-teste "Testes diagnósticos"){aria-label="Testes diagnósticos"}

{{< fa file-powerpoint size=lg >}} [Testes diagnósticos](/aulas/Testes%20diagnósticos/testesDiagnosticos.html#/combinação-em-paralelo "Testes diagnósticos"){aria-label="Testes diagnósticos"}