---
title: "Semana 06"
---

## Para ler antes da aula...

{{< fa file-pdf size=lg >}} [Fatores associados ao câncer de boca: um estudo de caso-controle em uma população do Nordeste do Brasil](/artigos/fatores_cancer_boca_caso_controle.pdf)

<!-- {{< fa file-pdf size=lg >}} [Prevalência e fatores associados ao bruxismo em universitários: um estudo transversal piloto](/artigos/Prevalência_fatores_associados_bruxismo_estudo_transversal.pdf) -->

## Leitura adicional

{{< fa file-pdf size=lg >}} [Entendendo a pesquisa clínica IV: Estudos de caso controle](/artigos/Entendendo_estudos_caso_controle.pdf)

<!-- {{< fa file-pdf size=lg >}} [Tópicos de metodologia de pesquisa: Estudos de corte transversal](/artigos/Entendendo_estudos_transversais.pdf) -->

### Probabilidade ou chance?

Probabilidade e chance são conceitos relacionados, mas não exatamente sinônimos! Leia os artigos abaixo e descubra mais sobre esse assunto.

{{< fa file-pdf size=lg >}} [Probabilidade ou chance?](/artigos/Probabilidade_ou_chance_01.pdf)

{{< fa file-pdf size=lg >}} [Probabilidade ou chance?](/artigos/Probabilidade_ou_chance.pdf)


## Tabela qui-quadrado

{{< fa table size=lg >}}[Tabela Qui-quadrado](/documentos/Tabela da Qui-quadrado.pdf)

## Slides

{{< fa file-powerpoint size=lg >}} [Estudos caso-controle](/aulas/Planejamento/#/estudo-caso-controle "Estudo caso-controle"){aria-label="Estudo caso-controle"}

<!-- {{< fa file-powerpoint size=lg >}} [Estudos transversais](/aulas/Planejamento/#/estudos-transversais "Estudos transversais"){aria-label="Estudos transversais"} -->