---
title: "Semana 04"
---

## Para ler antes da aula...

{{< fa file-pdf size=lg >}} [Coronavírus e o Coração | Um Relato de Caso sobre a Evolução da COVID-19 Associado à Evolução Cardiológica](/artigos/relato_de_caso_coronavirus_coracao.pdf)

{{< fa file-pdf size=lg >}} [Impacto da hospitalização na funcionalidade de idosos: estudo de coorte](/artigos/impacto_funcionalidade_idosos_estudo_coorte.pdf)

## Leitura adicional

{{< fa file-pdf size=lg >}} [Entendendo a pesquisa clínica V: relatos e séries de casos](/artigos/relato_serie_de_casos.pdf)

{{< fa file-pdf size=lg >}} [Entendendo a pesquisa clínica III: estudos de coorte](/artigos/Entendendo_estudos_coorte.pdf)

## Slides

{{< fa file-powerpoint size=lg >}} [Relato e Séries de casos](/aulas/Planejamento/index.html "Relato e Séries de casos"){aria-label="Relato e Séries de casos"}

{{< fa file-powerpoint size=lg >}} [Estudos de coorte](/aulas/Planejamento/#/estudos-observacionais-analíticos "Estudos de coorte"){aria-label="Estudos de coorte"}