project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "EST104 - Estatística Aplicada à Saúde"
  description: "Homepage da disciplina EST104 - Estatística Aplicada à Saúde, 2024/2."
  site-url: "http://professortp.com.br/est104/"

  repo-url: https://github.com/tiagomartin/est104
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "Página construída usando [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Tiago Pereira"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - aulas.qmd
      - estudos.qmd
      - analises.qmd
      - plano.qmd

      
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual