---
title: "Cronograma da disciplina"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

Esta página contém um esboço dos tópicos, conteúdos e tarefas para o semestre. Este cronograma será atualizado conforme o semestre avança.

<!-- https://fontawesome.com/search?o=r&m=free -->
<!-- https://jpswalsh.github.io/academicons/ -->


<!-- [{{< fa file-pdf size=2xl >}}](/weeks/week-1.html#prepare){aria-label="Week 1 summary"}  |  [️](/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"}  |       [{{< fa laptop-file size=2xl >}}](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"} -->

<!-- {{< fa brands r-project size=2xl >}}  -  scripts -->
<!-- {{< fa file-powerpoint size=2xl >}}   -  slides -->
<!-- {{< fa laptop-file size=2xl >}}  -  estudo de caso -->
<!-- {{< fa file-pdf size=2xl >}}  -  artigo -->

::: column-screen-inset-right
| Semana | Data | Tópico | Artigo | Slides |EC |LE |Script  | Avaliação | Projeto |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
|  [1](programacao/semana-1.html)  | Seg, 11/11 | Apresentação da disciplina |  |  |  |  | | 
|     | Qua, 13/11  | Não haverá aula! |         |  | | | | | 
|  [2](programacao/semana-2.html)  | Seg, 18/11 | Conceitos básicos |  | [{{< fa file-powerpoint size=2xl >}}️](aulas/Conceitos%20básicos/index.html "Conceitos básicos"){aria-label="Conceitos básicos"}        |  |  |   |
|                           | Qua, 20/11 | Conceitos básicos |  | [{{< fa file-powerpoint size=2xl >}}️](aulas/Conceitos%20básicos/index.html "Conceitos básicos"){aria-label="Conceitos básicos"}   |[ {{< fa laptop-file size=2xl >}}](estudos_de_casos/estudo01.html "Estudo de caso 01"){aria-label="Estudo de caso 01"}  |  |  |  |   
|  [3](programacao/semana-3.html)  | Seg, 25/11 | Conceitos básicos |  | [{{< fa file-powerpoint size=2xl >}}️](aulas/Conceitos%20básicos/index.html "Conceitos básicos"){aria-label="Conceitos básicos"}        |  |  |   |
|                           | Qua, 27/11 | Conceitos básicos |  | [{{< fa file-powerpoint size=2xl >}}️](aulas/Conceitos%20básicos/index.html "Conceitos básicos"){aria-label="Conceitos básicos"}   |[ {{< fa laptop-file size=2xl >}}](estudos_de_casos/estudo02.html "Estudo de caso 02"){aria-label="Estudo de caso 02"}  |  | [{{< fa brands r-project size=2xl >}}](/analise_dados/recem_nascidos.html "Script análise de dados"){aria-label="Script análise de dados"} |  |   
|  [4](programacao/semana-4.html)  | Seg, 02/12 | Relato (Série) de casos | [{{< fa file-pdf size=2xl >}}](artigos/relato_de_caso_coronavirus_coracao.pdf) | [{{< fa file-powerpoint size=2xl >}}️](/aulas/Planejamento/index.html "Relato e Séries de casos"){aria-label="Relato e Séries de casos"}    |  |  ||   
|                           | Qua, 04/11 | Estudos de coorte | [{{< fa file-pdf size=2xl >}}](artigos/impacto_funcionalidade_idosos_estudo_coorte.pdf) | [{{< fa file-powerpoint size=2xl >}}️](/aulas/Planejamento/#/estudos-observacionais-analíticos "Estudos de coorte"){aria-label="Estudos de coorte"}  |  |  |  |  |  
:::

```{r echo = FALSE}
knitr::knit_exit()
```
