{
  "hash": "7a06c3c99dd1bfde74aa41113af54863",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análise de dados: Avaliação de um Teste Diagnóstico para Diabetes\"\nlang: pt\ntoc: true\ncode-annotations: \"hover\"\n---\n\n## Contexto do Problema\n\n\nUm novo teste diagnóstico para diabetes foi desenvolvido por uma equipe de pesquisadores. Esse teste visa detectar a presença da doença com maior eficiência e menor custo em comparação ao teste de referência, que é o exame de glicemia em jejum. Antes de sua implementação na prática clínica, é necessário avaliar sua acurácia diagnóstica.\n\n\n## Objetivo do Estudo\n\n\nAvaliar a performance do novo teste diagnóstico em relação ao padrão-ouro (exame de glicemia em jejum).\n\n\n## Metodologia\n\n### Amostra do Estudo\n\nForam selecionados 500 indivíduos aleatoriamente em uma unidade de saúde. Cada participante realizou tanto o novo teste diagnóstico quanto o exame de glicemia em jejum.\n\n### Coleta de Dados\n\nOs participantes foram classificados em dois grupos:\n\n- Doença presente: Indivíduos diagnosticados com diabetes pelo exame de glicemia em jejum.\n- Doença ausente: Indivíduos sem diagnóstico de diabetes pelo exame de glicemia em jejum.\n\n\nOs resultados do novo teste diagnóstico foram comparados ao exame de glicemia em jejum para determinar a acurácia do teste.\n\n\nFonte dos dados:\n\n- <https://raw.githubusercontent.com/tiagomartin/est104/refs/heads/master/dados/teste_diabetes.csv>\n\n\n\n### Carregando os pacotes R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  rio,          # importa arquivos\n  tidyverse,    # gestão dos dados + gráficos no ggplot2 \n  janitor,      # adiciona números absolutos e porcentagens às tabelas\n  pROC,         # construção da curva ROC\n  epiR,         # cálculo das métricas de avaliação\n  cutpointr     # grafico da curva ROC\n  )\n```\n:::\n\n### Carregando os dados\n\n::: {.cell}\n\n```{.r .cell-code}\ndados = rio::import(\"https://raw.githubusercontent.com/tiagomartin/est104/refs/heads/master/dados/teste_diabetes.csv\") \n\ndados %>% \n  str()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t500 obs. of  4 variables:\n $ V1            : int  1 2 3 4 5 6 7 8 9 10 ...\n $ doenca        : int  0 1 0 1 1 0 0 1 0 0 ...\n $ teste_positivo: int  0 1 0 1 1 0 0 1 0 0 ...\n $ glicemia      : num  73.2 147.8 103.1 110.3 165.7 ...\n```\n\n\n:::\n:::\n\n### Tabela de contingência das variáveis doença e teste positivo\n\n::: {.cell}\n\n```{.r .cell-code}\ntabela = table(Referencia = dados$doenca, Teste = dados$teste_positivo)\n  \ntabela\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Teste\nReferencia   0   1\n         0 278  27\n         1  20 175\n```\n\n\n:::\n:::\n\n### Cálculo das Métricas\n\n::: {.cell}\n\n```{.r .cell-code}\nmetr = epi.tests(tabela)\n\nmetr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Outcome +    Outcome -      Total\nTest +          278           27        305\nTest -           20          175        195\nTotal           298          202        500\n\nPoint estimates and 95% CIs:\n--------------------------------------------------------------\nApparent prevalence *                  0.61 (0.57, 0.65)\nTrue prevalence *                      0.60 (0.55, 0.64)\nSensitivity *                          0.93 (0.90, 0.96)\nSpecificity *                          0.87 (0.81, 0.91)\nPositive predictive value *            0.91 (0.87, 0.94)\nNegative predictive value *            0.90 (0.85, 0.94)\nPositive likelihood ratio              6.98 (4.91, 9.93)\nNegative likelihood ratio              0.08 (0.05, 0.12)\nFalse T+ proportion for true D- *      0.13 (0.09, 0.19)\nFalse T- proportion for true D+ *      0.07 (0.04, 0.10)\nFalse T+ proportion for T+ *           0.09 (0.06, 0.13)\nFalse T- proportion for T- *           0.10 (0.06, 0.15)\nCorrectly classified proportion *      0.91 (0.88, 0.93)\n--------------------------------------------------------------\n* Exact CIs\n```\n\n\n:::\n:::\n\n## Discussão dos Resultados\n\nA prevalência real ($pr$) de diabetes é função dos resultados do exame de referência enquanto que a prevalência aparente ($pa$) é função dos resultados da aplicação do teste, ou seja,  \n\n$$pr = \\dfrac{298}{500} \\approx 0,60  \\text{           e          } pa = \\dfrac{305}{500} = 0,61$$ \n\nO novo teste diagnóstico apresentou alta sensibilidade (93%), indicando que ele identifica corretamente a maioria dos indivíduos com diabetes. A especificidade de 87% sugere que o teste também é eficaz em descartar aqueles sem a doença.\n\nOs valores preditivos indicam a confiabilidade dos resultados do teste: 91% das pessoas com teste positivo realmente têm diabetes, enquanto 90% das pessoas com teste negativo realmente não têm a doença.\n\nA acurácia global de 91% sugere que o teste é uma ferramenta útil, mas deve ser avaliado em combinação com outros fatores clínicos antes de sua adoção generalizada.\n\nNote que o valor $RV_+ = 6,98$ indica que um resultado positivo é aproximadamente 7 vezes mais provável em pacientes com diabetes do que os não doentes, enquanto que o resultado negativo ($RV_- = 0,08$) é 12,5 vezes $\\left( \\dfrac{1}{0,08}=12,5 \\right)$ mais provável em pacientes não doentes.\n\n### Outras interpretações\n\n- False $T_+$ proportion for true $D_-$ = 0,13: Proporção de falsos positivos ($PFP$) entre aqueles que realmente não têm a doença ($D_-$), ou seja, 13% das pessoas sem a doença foram classificadas erroneamente como positivas pelo teste. Um teste com alta proporção de falsos positivos pode levar a diagnósticos errôneos e ansiedade desnecessária para pacientes saudáveis. Se esse valor for alto, pode ser necessário aumentar a especificidade do teste.\n\n- False $T_-$ proportion for true $D_+$ = 0,07: Essa é a proporção de falsos negativos ($PFN$) entre aqueles que realmente têm a doença ($D_+$), ou seja, 7% das pessoas com a doença foram classificadas erroneamente como negativas pelo teste. Um teste com falsos negativos pode perder casos reais da doença, o que pode ser perigoso, especialmente se a doença exigir tratamento precoce. Se esse valor for alto, pode ser necessário aumentar a sensibilidade do teste.\n\n- False $T_+$ proportion for $T_+$ = 0,09: Essa é a proporção de falsos positivos entre todos os testes positivos ($T_+$), ou seja, entre todos os pacientes que tiveram um teste positivo, 9% eram na verdade saudáveis. Isso afeta o Valor Preditivo Positivo ($VPP$). Se essa proporção for alta, significa que um teste positivo nem sempre confirma a doença.\n\n- False $T_-$ proportion for $T_-$ = 0,10: Essa é a proporção de falsos negativos entre todos os testes negativos ($T_-$), ou seja, entre todos os pacientes que tiveram um teste negativo, 10% na verdade tinham a doença. Isso afeta o Valor Preditivo Negativo ($VPN$). Se essa proporção for alta, significa que um teste negativo nem sempre exclui a doença.\n\n### Índice de Youden e *Odds Ratio*\n\n::: {.cell}\n\n```{.r .cell-code}\nmetr$detail\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   statistic         est       lower       upper\n1         ap  0.61000000  0.56569956   0.6529917\n2         tp  0.59600000  0.55152589   0.6393322\n3         se  0.93288591  0.89824865   0.9585262\n4         sp  0.86633663  0.81151436   0.9100326\n5    diag.ac  0.90600000  0.87696239   0.9301138\n6    diag.or 90.09259259 49.03156269 165.5398032\n7       nndx  1.25121596  1.15133247   1.4089210\n8     youden  0.79922254  0.70976302   0.8685588\n9     pv.pos  0.91147541  0.87381587   0.9408505\n10    pv.neg  0.89743590  0.84604758   0.9362173\n11    lr.pos  6.97936863  4.90648290   9.9280049\n12    lr.neg  0.07746884  0.05055819   0.1187032\n13    p.rout  0.39000000  0.34700826   0.4343004\n14     p.rin  0.61000000  0.56569956   0.6529917\n15    p.tpdn  0.13366337  0.08996739   0.1884856\n16    p.tndp  0.06711409  0.04147376   0.1017513\n17    p.dntp  0.08852459  0.05914948   0.1261841\n18    p.dptn  0.10256410  0.06378268   0.1539524\n```\n\n\n:::\n:::\n\nTemos que o índice de Youden foi igual a 0,80 (0,71;0,87), indicando que o novo teste é um excelente, altamente confiável para o diagnóstico de diabetes. Temos ainda que, a *odds ratio* foi igual a 90,09 (49,03; 165,54), indicando que a chance de um resultado de teste positivo é de 90 vezes em pacientes com diabetes em relação à do grupo sem a doença.\n\n\n\n### Intervalos de confiança\n\n\n1) Intervalo de Confiança para Sensibilidade, Especificidade, VPP, VPN e Proporções\n\n\nEssas métricas seguem uma distribuição binomial, e o intervalo de confiança pode ser calculado usando a fórmula do IC binomial de Wald:\n\n$$IC = \\hat{p} \\pm z_{\\frac{\\alpha}{2}} \\times \\sqrt{\\dfrac{\\hat{p}(1-\\hat{p})}{n}}$$\n\nem que,\n\n- $\\hat{p}$ é a estimativa da proporção (por exemplo: sensibilidade = 0,93).\n- $z_{\\frac{\\alpha}{2}}$ é o valor crítico da distribuição normal para um nível de confiança de $(1 - \\alpha)$% (1,96 para 95%).\n- $n$ é o número total de indivíduos no grupo correspondente (por exemplo: para sensibilidade, n = 298).\n\n\n2) Intervalo de Confiança para Razões de Verossimilhança (Likelihood Ratios)\n\n\nOs $RV_+$ e $RV_-$ não seguem diretamente uma distribuição binomial, então aplicamos a transformação logarítmica para calcular o IC:\n\n$$IC = \\exp(\\ln(\\hat{RV}) \\pm  z_{\\frac{\\alpha}{2}}  \\times SE)$$\n\nem que o erro padrão ($SE$) é dado por\n\n$$SE = \\sqrt{\\dfrac{1}{a} - \\dfrac{1}{a+b} + \\dfrac{1}{d} - \\dfrac{1}{c+d}}$$\n\n\n3) Intervalo de Confiança para o Índice de Youden\n\n\nPara calcular o intervalo de confiança (IC) do Índice de Youden, usamos a seguinte fórmula:\n\n$$SE_J = \\sqrt(SE^2_s + SE_e^2)$$\nsendo $SE_s$ o erro paddrão da sensibilidade e $SE_e$, o r=erro padrão da especificidade. Assim, o IC do Índice de Youden é dado por:\n\n$$IC = J \\pm z_{\\frac{\\alpha}{2}} \\times SE_J$$\n\n\n4) Intervalo de confiança para *odds ratio*\n\n\nO intervalo de confiança para o $OR$, pode ser calculado com a seguinte fórmula:\n\n$$IC = \\exp(\\ln(OR) \\pm z_{\\frac{\\alpha}{2}} \\times SE_{\\ln(OR)})$$\nsendo\n\n$$SE_{\\ln(OR)} = \\sqrt{\\dfrac{1}{a} + \\dfrac{1}{b} + \\dfrac{1}{c} + \\dfrac{1}{d}}$$\n\n## E se a variável desfecho for contínua?\n\n\nVamos considerar a variável *Índice de Glicemia* para avaliação do diagnóstico.\n\n\n### Curva ROC e Área Sob a Curva (AUC)\n\n::: {.cell}\n\n```{.r .cell-code}\nroc_obj = pROC::roc(dados$doenca, dados$glicemia)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting levels: control = 0, case = 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting direction: controls < cases\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(roc_obj, main = \"Curva ROC do Teste Diagnóstico\")\n```\n\n::: {.cell-output-display}\n![](teste_diabetes_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\nauc_valor = pROC::auc(roc_obj)\n\n##Área sob a Curva (AUC)\nauc_valor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.9901\n```\n\n\n:::\n:::\n\n\nA Curva ROC (Receiver Operating Characteristic) avalia a capacidade do teste em distinguir entre pacientes com e sem diabetes. O principal indicador de performance é a Área Sob a Curva (AUC):\n\n- AUC = 1.0 → Teste perfeito (classifica todos corretamente).\n- AUC ≥ 0.9 → Teste excelente.\n- AUC entre 0.8 e 0.9 → Teste muito bom.\n- AUC entre 0.7 e 0.8 → Teste razoável.\n- AUC entre 0.5 e 0.7 → Teste fraco.\n- AUC = 0.5 → O teste não tem poder discriminatório (equivalente ao acaso).\n\n\nSe obtivermos, por exemplo, AUC = 0,9901, isso indica que o teste tem um excelente desempenho em distinguir pacientes com e sem diabetes.\n\n\n### Escolha do Melhor Ponto de Corte\n\n\nUm teste com desfecho contínuo precisa de um ponto de corte para ser usado na prática clínica. O índice de Youden é um critério comum para encontrar o limiar ideal:\n\n\n$$J = Sensibilidade+Especificidade−1$$\n\nO melhor ponto de corte é aquele que maximiza simultaneamente a sensibilidade e a especificidade. Se priorizamos detectar todos os casos (sensibilidade alta), podemos escolher um ponto de corte mais baixo. Se queremos evitar falsos positivos, podemos escolher um ponto de corte mais alto. \n\n::: {.cell}\n\n```{.r .cell-code}\ncp = cutpointr(dados,  glicemia, doenca, \n                method = maximize_metric, metric = youden)# <1>\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nAssuming the positive class is 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nAssuming the positive class has higher x values\n```\n\n\n:::\n\n```{.r .cell-code}\ncp$optimal_cutpoint\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 117.7534\n```\n\n\n:::\n:::\n1. A função cutpointr() do pacote *cutpointr* determina e avalia pontos de corte ideais baseados em uma métrica específica. Para uma introdução ao pacote, consulte vignette(\"cutpointr\", package = \"cutpointr\").\n\n\nPodemos observar que para este exemplo, o ponto de corte ótimo foi igual a 117,7534, indicando que pacientes com valores acima desse limite são mais propensos a ter diabetes, enquanto valores abaixo desse limite indicam baixo risco.\n\n::: {.cell}\n\n```{.r .cell-code}\n## Algumas métricas de avaliação\n\nsummary(cp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMethod: maximize_metric \nPredictor: glicemia \nOutcome: doenca \nDirection: >= \n\n    AUC   n n_pos n_neg\n 0.9901 500   195   305\n\n optimal_cutpoint youden   acc sensitivity specificity  tp fn fp  tn\n         117.7534 0.9164 0.958       0.959      0.9574 187  8 13 292\n\nPredictor summary: \n    Data     Min.        5%   1st Qu.    Median      Mean   3rd Qu.      95%\n Overall 45.75192  69.90402  85.84629 101.76185 112.67595 140.95893 170.6583\n       0 45.75192  66.15261  80.00629  88.80496  89.59556  98.61755 116.4540\n       1 93.02906 119.23256 137.15388 148.79227 148.77605 162.67633 177.8412\n     Max.       SD NAs\n 190.8391 33.28575   0\n 141.3164 15.06062   0\n 190.8391 18.62637   0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Curva roc\n\nplot(cp)\n```\n\n::: {.cell-output-display}\n![](teste_diabetes_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nSe o objetivo for detectar o máximo de casos de diabetes (exemplo: triagem populacional), escolhemos um ponto de corte com alta sensibilidade (aceitando mais falsos positivos). Se o objetivo for garantir que apenas os verdadeiros doentes sejam diagnosticados (exemplo: evitar sobretratamento), escolhemos um ponto de corte com alta especificidade  (aceitando mais falsos negativos). Em muitos casos clínicos, o ponto de corte pode ser ajustado com base em fatores de risco individuais.\n",
    "supporting": [
      "teste_diabetes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}