---
title: "Estudo de Caso: Desgaste de lentes de contato"
lang: pt
toc: true
code-annotations: "hover"
bibliography: references.bib
---

@coles02 abordaram a possibilidade das novas lentes de contato gelatinosas tratadas com uma solução de condicionamento oferesem um maior grau de conforto ao paciente do que lentes semelhantes sem esse tratamento. Para isso,

> Sessenta e um usuários experientes de lentes de contato com características oculares incomuns foram recrutados no banco de dados de indivíduos da Breman Consultants e por anúncios em jornais locais. Para serem elegíveis para participar do estudo, os indivíduos tinham que ter pelo menos 18 anos de idade e estar usando lentes de contato gelatinosas com sucesso por pelo menos um mês antes do estudo. Os míopes com até -12,00 D com menos de 0,75 D de anisometropia foram incluídos.

Os dados de 59 dos indivíduos, 24 homens e 35 mulheres, foram considerados apropriados para análise. A idade média desses indivíduos era de 31,5, com desvio padrão de 10,2.

Os pacientes foram categorizados como pertencentes a um de dois grupos, aqueles que no começo do estudo responderam com um "sim" à pergunta "Você é capaz de usar suas lentes de contato pelo tempo que desejar?" e aqueles que responderam negativamente à mesma pergunta. Os pacientes nas duas categorias tiveram uma lente condicionada colocada em um olho escolhido aleatoriamente e uma lente não condicionada colocada no outro olho. A ordem de inserção, isto é, lente condicionada primeiro ou lente não condicionada primeiro, também foi aleatória. Os pacientes não puderam saber qual das lentes era condicionada.

As lentes foram inseridas durante uma visita na parte da manhã ao local da pesquisa. Depois da inserção, os indivíduos responderam com qual lente eles se sentiam mais confortáveis. Aproximandamente oito horas depois, os indivíduos retornaram para uma visita à tarde, quando foram novamente questionados sobre a lente mais confortável. Os pacientes não poderiam indicar "nenhuma diferença", de modo que foram exigidas designações de escolha forçada. Os resultados para essa parte do estudo são dados na Tabela abaixo.


<center>
<style type="text/css">
.tg  {border-collapse:collapse;border-color:#ccc;border-spacing:0;}
.tg td{background-color:#fff;border-bottom-width:1px;border-color:#ccc;border-style:solid;border-top-width:1px;
  border-width:0px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;
  word-break:normal;}
.tg th{background-color:#f0f0f0;border-bottom-width:1px;border-color:#ccc;border-style:solid;border-top-width:1px;
  border-width:0px;color:#333;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-abip{background-color:#f9f9f9;border-color:inherit;text-align:center;vertical-align:top}
</style>
<table class="tg"><thead>
  <tr>
    <th class="tg-c3ow" rowspan="2"></th>
    <th class="tg-c3ow" colspan="2">Não</th>
    <th class="tg-c3ow" colspan="2">Sim</th>
  </tr>
  <tr>
    <th class="tg-abip">Lente tratada</th>
    <th class="tg-abip">Lente não tratada</th>
    <th class="tg-abip">Lente tratada</th>
    <th class="tg-abip">Lente não tratada</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-c3ow">Manhã</td>
    <td class="tg-c3ow">10</td>
    <td class="tg-c3ow">2</td>
    <td class="tg-c3ow">23</td>
    <td class="tg-c3ow">24</td>
  </tr>
  <tr>
    <td class="tg-abip">Tarde</td>
    <td class="tg-abip">7</td>
    <td class="tg-abip">5</td>
    <td class="tg-abip">26</td>
    <td class="tg-abip">21</td>
  </tr>
</tbody>
</table>
</center>


Na tabela, "não" significa não para a pergunta de duração, "sim" significa sim para a pergunta de duração, "lente tratada" significa que o indivíduo escolheu a lente tratada com solução de condicionamento, "lente não tratada" significa que o indivíduo escolheu a lente sem solução de condicionamento, "manhã" significa que a avaliação foi feita durante a visita da manhã, e "tarde" significa que a avaliação foi feita durante a visita da tarde.

Além desses dadosm diversas variáveis de saúde ocular foram avaliadas para cada olho em cada visita. Essas medições constituem uma escala contínua.

Baseado nesse estudo de caso, responda as seguintes questões:

1. Identifique a amostra nesse estudo.

2. A população nesse estudo é bem identificada? Justifique sua resposta.

3. Descreva a população da melhor forma possível.

4. Podemos encontrar uma estatística descritiva nesse estudo? Se sim, dê exemplos.

5. Podemos encontrar um parâmetro nesse estudo? Se sim, dê exemplos; se não, explique o motivo.

6. Podemos encontrar algum dado nesse estudo? Se sim, dê exemplos.